Se crea el microservicio Api-products con las dependencias adecuadas.
Team-6-R-L-Academy-Backend/api-products pull request #1
Opened 2024-06-05 21:31 UTC by BryanChugcho

2024-06-05 21:36 UTC, LeanBaier requested changes

2024-06-05 21:36 UTC, LeanBaier commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Formatear pom.xml con el formatter del proyecto

2024-06-05 21:36 UTC, LeanBaier commented on src/main/java/com/demo/api_products/ApiProductsApplication.java
> +package com.demo.api_products;
Renombrar package com.demo.api_products a com.demo.apiproducts para continuar con la misma nomenclatura que api users

2024-06-05 21:36 UTC, LeanBaier commented on mvnw
> +#!/bin/sh
Agregar archivo a .gitignore y eliminar del pr

2024-06-05 21:36 UTC, LeanBaier commented on mvnw.cmd
> +<# : batch portion
Agregar archivo a .gitignore y eliminar del pr

2024-06-05 21:36 UTC, LeanBaier commented on .mvn/wrapper/maven-wrapper.properties
> +# Licensed to the Apache Software Foundation (ASF) under one
Agregar archivo a .gitignore y eliminar del pr

2024-06-06 18:17 UTC, AntoCant approved these changes

2024-06-11 00:00 UTC, closed without merging