feature/RLA-12
Team-6-R-L-Academy-Backend/api-products pull request #10
Opened 2024-07-04 23:09 UTC by AntoCant

![image](https://github.com/Team-6-R-L-Academy-Backend/api-products/assets/126527251/20acf4b2-1be2-4510-a27a-bd3d7ae85b2d)

![image](https://github.com/Team-6-R-L-Academy-Backend/api-products/assets/126527251/0b5ad8bc-779c-4a1f-99a4-0cf4a3dfe8e9)

2024-07-04 23:50 UTC, marcosbuenocapillera approved these changes

2024-07-05 21:12 UTC, LeanBaier requested changes

2024-07-05 21:12 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/dtos/request/RequestHighProduct.java
> +public class RequestHighProduct implements Serializable {
Renombrar clase a RequestCreateProductDTO

2024-07-05 21:12 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/dtos/request/RequestHighProductImage.java
> +public class RequestHighProductImage implements Serializable {
Renombrar clase a RequestCreateProductImageDTO

2024-07-05 21:12 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/dtos/response/ResponseHighProduct.java
> +public class ResponseHighProduct implements Serializable  {
Renombrar clase a ResponseCreateProductDTO

2024-07-05 21:12 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/handler/IllegalArgumentExceptionErrorHandler.java
> +public class IllegalArgumentExceptionErrorHandler {
Utilizar un nombre mas generico para el errorHandler, por el nombre solo podriamos utilizar una exception dentro de esta clase

2024-07-05 21:12 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +      }
Crear exceptions especificas para los casos de validacion

2024-07-05 21:12 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +                                     .build();
Llevar a un mapper

2024-07-05 21:12 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +                 .build();
Llevar a un mapper

2024-07-05 21:12 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +                                .build();
Llevar a un mapper

2024-07-05 21:12 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +      rlProductImageRepository.saveAll(rlProduct.getProductImages());
Almacenar directamente con el producto, no hace falta guardar las imagenes por separado

2024-07-05 21:19 UTC, LeanBaier requested changes

2024-07-05 21:19 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/dtos/request/RequestHighProductImage.java
> +   private Boolean principal;
Agregar validaciones

2024-07-05 21:19 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/dtos/request/RequestHighProduct.java
> +   @NotBlank
@NotBlank es solamente para String

2024-07-06 22:30 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/dtos/request/RequestHighProduct.java
> +public class RequestHighProduct implements Serializable {
refactorizado

2024-07-06 22:30 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/dtos/request/RequestHighProductImage.java
> +public class RequestHighProductImage implements Serializable {
refactorizado

2024-07-06 22:30 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/dtos/response/ResponseHighProduct.java
> +public class ResponseHighProduct implements Serializable  {
refactorizado

2024-07-06 22:47 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/dtos/request/RequestHighProductImage.java
> +   private Boolean principal;
se agregaron validaciones

2024-07-06 22:48 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/dtos/request/RequestHighProduct.java
> +   @NotBlank
se cambia por @notnull

2024-07-06 22:50 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/handler/IllegalArgumentExceptionErrorHandler.java
> +public class IllegalArgumentExceptionErrorHandler {
se cambio nombrer a GlobalExceptionErrorHandler

2024-07-07 00:50 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +      rlProductImageRepository.saveAll(rlProduct.getProductImages());
listo

2024-07-07 00:50 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +                                .build();
listo

2024-07-07 00:50 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +                 .build();
listo

2024-07-07 00:50 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +                                     .build();
listo

2024-07-07 01:06 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +      }
listo

2024-07-07 18:06 UTC, merged