Feature/rla 6
Team-6-R-L-Academy-Backend/api-products pull request #4
Opened 2024-06-14 19:32 UTC by HernanCaggiano

Se creo el servicio de consulta de productos, con sus DTO y controller, se creo la clase ProductSpecifications para consultas y filtrados mediante el uso de la API de JPA. Se agrego una nueva tabla de favoritos a la BD.
![reporte service](https://github.com/Team-6-R-L-Academy-Backend/api-products/assets/103146111/0d7e1540-ebc0-41c4-a1e4-62b4cd323d4d)

2024-06-15 01:24 UTC, marcosbuenocapillera commented
Segun el ticket pide 'se buscan solo los productos favoritos del usuario' ,  no hay consulta del usuario actual, confirmar con Lean si todas las consultas hay que filtrar por el usuario autenticado?

2024-06-18 21:18 UTC, AntoCant requested changes
Tambien te voy a pedir que cambies el package dto a dtos ( como venimos usando) y agregar sus dos packages  internos que son request y response. Agregar tus dtos según corresponda ya sea en request o response.
Agregar indentacion en todas las clases. Recorda que el archivo que usamos esta en le grupo.
Fijate que la foto que mandaste en la parte de favorito no corresponde a lo pedido en el requisito.

2024-06-18 21:18 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/controller/ProductController.java
> +@RequestMapping("/api/v1/products")
- Corregir @RequestMapping debería contener solo "/api/v1" 
- Agregar anotacion @RequiredArgsConstructor , para inyectar las dependencias como final

2024-06-18 21:18 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/controller/ProductController.java
> +   private ProductService productService;
Sacar anotación @Autowired y usar final

2024-06-18 21:18 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/controller/ProductController.java
> +           @RequestParam(value = "size", defaultValue = "10") int size
Agregar anotaciones de Max y Min

2024-06-18 21:18 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/dto/ProductDTO.java
> +@Setter
Usar la anotaciones que venimos usando 
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor

2024-06-18 21:18 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/dto/ProductDTO.java
> +public class ProductDTO {
Agregar (implements Serializable)

2024-06-18 21:18 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/dto/ProductResponse.java
> +public class ProductResponse {
Usar la anotaciones que venimos usando
@DaTa
@builder
@NoArgsConstructor
@AllArgsConstructor
Agregar (implements Serializable)

2024-06-18 21:18 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/dto/ProductTypeDTO.java
> +public class ProductTypeDTO {
Usar la anotaciones que venimos usando
@DaTa
@builder
@NoArgsConstructor
@AllArgsConstructor
Agregar (implements Serializable)

2024-06-18 21:18 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/dto/ProductResponse.java
> +   }
Sacar constructor con las anotaciones no seria necesario

2024-06-18 21:18 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/dto/ProductTypeDTO.java
> +   }
Sacar constructor con las anotaciones no seria necesario

2024-06-18 21:18 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/service/ProductService.java
> +public class ProductService {
Agregar anotacion @RequiredArgsConstructor para inyectar las depencias con final como veniamos haciendo

2024-06-18 21:18 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/service/ProductService.java
> +   }
Sacar @Autowired y el constructor. Usar final

2024-06-18 21:18 UTC, AntoCant commented on src/main/resources/scripts/createApiProductsSchema.sql
> +    large_description  text not null,
No modificar script existente. Agregar script con las modificaciones a las tablas existentes

2024-06-18 21:18 UTC, AntoCant commented on src/main/resources/scripts/createApiProductsSchema.sql
> +);
Deberia ser un Script nuevo

2024-06-18 21:18 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/dto/ProductDTO.java
> +   }
Sacar constructor con las anotaciones no seria necesario

2024-06-18 21:18 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/dto/FavoriteDTO.java
> +public class FavoriteDTO {
Usar la anotaciones que venimos usando
@DaTa
@builder
@NoArgsConstructor
@AllArgsConstructor
Agregar (implements Serializable)

2024-06-18 21:18 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/controller/ProductController.java
> +      }
La lógica debería ir solo en el service

2024-07-02 04:17 UTC, AntoCant commented
![image](https://github.com/Team-6-R-L-Academy-Backend/api-products/assets/126527251/d61be04f-57a2-4cc4-ba8e-7efd377c00da)

2024-07-02 14:56 UTC, LeanBaier requested changes

2024-07-02 14:56 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/mapper/RlProductImageMapper.java
> +                          .collect(Collectors.joining(", "));
se devuelve solo el link principal, coordinar con el servicio de alta

2024-07-02 14:56 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +      }
Los filtros se deben aplicar en las queries

2024-07-03 03:35 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +      }
se cambiaron los filtros

2024-07-03 21:20 UTC, LeanBaier requested changes

2024-07-03 21:20 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +      }
Refactorizar para evitar n llamados a la base de datos

2024-07-03 21:20 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/specifications/ProductSpecifications.java
> +         }
Contemplar flag isFavorite en la specification

2024-07-07 21:58 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/mapper/RlProductImageMapper.java
> +                          .collect(Collectors.joining(", "));
listo

2024-07-07 21:58 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +      }
listo

2024-07-07 21:58 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/specifications/ProductSpecifications.java
> +         }
listo

2024-07-07 21:58 UTC, merged