get product by id
Team-6-R-L-Academy-Backend/api-products pull request #7
Opened 2024-06-23 19:37 UTC by AntoCant

![image](https://github.com/Team-6-R-L-Academy-Backend/api-products/assets/126527251/2d6b6a2b-090f-4e14-a622-8c9243ed2b5b)

2024-06-24 02:19 UTC, marcosbuenocapillera approved these changes

2024-06-25 20:57 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/config/SecurityConfig.java
> +                                                 .permitAll())
anyRequest deberia ser authenticated()
hacer un permitAll para swagger

2024-06-25 21:00 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/dtos/response/ResponseProductByIdDTO.java
> +@JsonPropertyOrder({"idProduct", "name", "productType", "currency", "price", "images", "isFavorite", "description", "largeDescription"})
Sacar JsonPropertyOrder

2024-06-25 21:04 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +      }
Injectar Authentication desde el controller, recibir en el service el username

2024-06-26 03:01 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/config/SecurityConfig.java
> +                                                 .permitAll())
de modifico para permitir Swagger, se agregaron dependencias correctas para el correcto funcionamiento

2024-06-26 03:01 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/dtos/response/ResponseProductByIdDTO.java
> +@JsonPropertyOrder({"idProduct", "name", "productType", "currency", "price", "images", "isFavorite", "description", "largeDescription"})
realizado

2024-06-26 03:01 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +      }
Realizado

2024-06-26 21:25 UTC, LeanBaier requested changes

2024-06-26 21:25 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/config/SecurityConfig.java
> +                                                 .authenticated())
Contemplar el resto de los endpoints autenticados

2024-06-26 21:25 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/controller/RlProductController.java
> +      }
El objeto Authentication se tiene que recibir como parametro de la funcion

2024-06-26 23:36 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/config/SecurityConfig.java
> +                                                 .authenticated())
listo, así queda todo securizado y solo queda libre lo que esta en la especificación de match

2024-06-26 23:37 UTC, AntoCant commented on src/main/java/com/demo/apiproducts/controller/RlProductController.java
> +      }
se agrega inyección dentro de del parametro

2024-06-27 14:52 UTC, marcosbuenocapillera approved these changes

2024-06-27 21:42 UTC, LeanBaier approved these changes

2024-06-27 21:42 UTC, merged