Feature/RLA14
Team-6-R-L-Academy-Backend/api-products pull request #8
Opened 2024-06-28 14:52 UTC by marcosbuenocapillera

![image](https://github.com/Team-6-R-L-Academy-Backend/api-products/assets/144061559/d29cd29d-f598-47e3-ab50-4c796a5ebb96)

2024-06-28 21:21 UTC, YesiPerezz approved these changes

2024-06-28 21:41 UTC, YesiPerezz approved these changes

2024-07-01 14:07 UTC, LeanBaier requested changes

2024-07-01 14:07 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/controller/RlProductController.java
> +import java.util.Map;
Revisar los imports:
- no hay que usar imports con *
- no veo que se este usando el Map, si no es necesario quitarlo

2024-07-01 14:07 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +@Transactional
Por que se hizo transactional el service?

2024-07-01 14:07 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/dtos/response/request/RequestProductDailyofferDTO.java
> +}
Le faltan campos al DTO? si no es necesario eliminarlo

2024-07-01 14:07 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +   }
Utilizar MapStruct

2024-07-01 20:28 UTC, marcosbuenocapillera commented on src/main/java/com/demo/apiproducts/controller/RlProductController.java
> +import java.util.Map;
Corregido

2024-07-01 20:28 UTC, marcosbuenocapillera commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +@Transactional
Corregido

2024-07-01 20:28 UTC, marcosbuenocapillera commented on src/main/java/com/demo/apiproducts/dtos/response/request/RequestProductDailyofferDTO.java
> +}
No entendi eso.

2024-07-01 20:28 UTC, marcosbuenocapillera commented on src/main/java/com/demo/apiproducts/service/RlProductService.java
> +   }
Corregido

2024-07-03 21:25 UTC, LeanBaier requested changes

2024-07-03 21:25 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/repository/ProductRepository.java
> +@Transactional
a que se debe el transactional?

2024-07-03 21:25 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/repository/ProductRepository.java
> +    @Query(nativeQuery = true, value = "UPDATE rl_api_products.rl_product SET daily_offer = false WHERE daily_offer = true")
Usar JPQL, evitar usar nativeQuery

2024-07-03 21:25 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/repository/ProductRepository.java
> +    @Query(nativeQuery = true, value = "UPDATE rl_api_products.rl_product SET daily_offer = ?2 WHERE id_rl_product = ?1")
Usar JPQL, evitar usar nativeQuery

2024-07-03 21:47 UTC, LeanBaier requested changes

2024-07-03 21:47 UTC, LeanBaier commented on src/main/java/com/demo/apiproducts/dtos/response/request/RequestProductDailyofferDTO.java
> +
Agregar validaciones para que no sea null

2024-07-04 00:41 UTC, marcosbuenocapillera commented on src/main/java/com/demo/apiproducts/dtos/response/request/RequestProductDailyofferDTO.java
> +
Pronto

2024-07-04 00:41 UTC, marcosbuenocapillera commented on src/main/java/com/demo/apiproducts/repository/ProductRepository.java
> +    @Query(nativeQuery = true, value = "UPDATE rl_api_products.rl_product SET daily_offer = ?2 WHERE id_rl_product = ?1")
pronto

2024-07-04 00:41 UTC, marcosbuenocapillera commented on src/main/java/com/demo/apiproducts/repository/ProductRepository.java
> +    @Query(nativeQuery = true, value = "UPDATE rl_api_products.rl_product SET daily_offer = false WHERE daily_offer = true")
pronto

2024-07-04 20:52 UTC, LeanBaier approved these changes

2024-07-04 20:56 UTC, merged